Cartes = [
    "Issun-bōshi",
    "Petit Djinn",
    "Récupérateur Axiom",
    "Danseuse de Lames Bravos",
    "Ratatosk",
    "Prestidigitatrice de l'Ouroboros",
    "Chiron",
    "Dame du Lac",
    "Fée des Dents",
    "Hua Mulan",
    "Kitsune",
    "Ozma",
    "Pionnière Bravos",
    "Traceuse Bravos",
    "Armurière de la Fonderie",
    "Navigatrice Lyra",
    "Red",
    "Aspirant de Havre",
    "Espionne Ordis",
    "Avant-Garde Bravos",
    "Dracaena",
    "Guerrière de Havre",
    "Tanuki",
    "Tomoe Gozen",
    "Trois Petits Cochons",
    "Videuse Bravos",
    "Sun Wukong",
    "Parvati",
    "Puissant Jinn",
    "Aja",
    "Kappa",
    "Le Conseil",
    "Le Chapelier",
    "Dorothy Gale",
    "Achille",
    "Atlas",
    "Asmodée",
    "Fils d'Yggdrasil",
    "Shenlong",
    "Sakarabru",
    "Kaibara, Léviathan Asgarthi",
    "Lapin Ardent",
    "Le Bonhomme de Neige",
    "Seiringar de Havre",
    "Défricheur ou Sapeur Bravos",
    "La Petite Fille aux Allumettes",
    "Skadi",
    "Belasenka",
    "Saskia, Naturaliste Rusée",
    "Secouriste Bravos",
    "Gericht, Honoré Bretteur",
    "Yéti",
    "Aroro, Rempart d'Asgartha",
    "Puissant Simbi",
    "Akhlut",
    "Valémon",
    "Amarok",
    "Liéchi",
    "Benzaiten",
    "Demeter",
    "Eros",
    "Fouisseur Nouch",
    "Renifleur de Sève",
    "Petit Cuistot",
    "Fan de Bliss",
    "Corgi Câline",
    "Les Grems",
    "Pendekar Bravos",
    "Porteuse d'Esprit",
    "Excavateur Bravos",
    "Gestionnaire de Pénurie",
    "Dédale",
    "Skateuse Talarienne",
    "Chef Pâtissier",
    "Fiore dei Liberi",
    "Hestia",
    "Aoife, Avatar de Feu",
    "Hydre de Lerne",
    "Prototype Amélioré",
    "Djinn Fulgurant",
    "L'Affamé",
    "Thésée"
]

def ProcessString(String):
    return String.replace("é", "e").replace("è", "e").replace("ê", "e").replace("â", "a").replace("à", "a").replace("î", "i").replace("ō", "o").replace("ô", "o").lower().replace(",", "").replace("-", "").replace(" ", "").replace("'", "")

with open("./Altered/output.txt", "a", encoding = "utf-8") as f:
    for name in Cartes:
        f.write("python ./Altered/scraping_uniques.py -faction bravos -name \"" + name +"\" -radical \"" + ProcessString(name) + "\"\n")