Cartes = [
    "Disciple Studieux", 
    "Héraut de Papier", 
    "Martengale", 
    "Mage-Danseur du Kadigir", 
    "Comédien Lyra", 
    "Encrière de l'Ouroboros", 
    "Hathor", 
    "Kodama", 
    "Navigatrice Lyra", 
    "Pionnière Bravos", 
    "Prestidigitatrice de l'Ouroboros", 
    "Skald Lyra", 
    "Esmeralda", 
    "Fée Clochette", 
    "Anansi", 
    "Danseuse d'Étoffe Lyra", 
    "Le Marchand de Sable", 
    "Alice", 
    "Aloe Vera", 
    "Cernunnos", 
    "Chroniqueuse Lyra", 
    "Tanuki", 
    "Tomoe Gozen", 
    "Yong-Su, Tisserand Verdoyant", 
    "Dr Frankenstein", 
    "Flamel", 
    "Puissant Djinn", 
    "Croupière de l'Ouroboros", 
    "Kappa", 
    "Le Chapelier", 
    "Pignon Pugnace", 
    "Robin des Bois", 
    "Amahle, Paria Asgarthi", 
    "Asmodée", 
    "Shenlong", 
    "Loki", 
    "Hydracaena", 
    "Kaibara, Léviathan Asgarthi", 
    "Commando Boule-de-Neige", 
    "Entasseur Magpeng", 
    "Le Bonhomme de Neige", 
    "Pamola", 
    "Seiringar de Havre", 
    "Déblayeur Bravos", 
    "Nisse", 
    "Perséphone", 
    "Feu Follet", 
    "Nyala, Habile Illusionniste", 
    "Veilleur Ordis", 
    "Gericht, Bretteur Honoré", 
    "Heimdall", 
    "Le Père Noël", 
    "Griffonneur Étoilé", 
    "Fan de Bliss", 
    "Flore, Maraîchère Attentive", 
    "Bassiste de Bliss", 
    "Claviériste de Bliss", 
    "Contorsionniste Lyra", 
    "Drone Ratisseur", 
    "Tatoueur Yzmir", 
    "Dédale", 
    "La Petite Souris", 
    "Lakshmi", 
    "Arawn", 
    "Batteur de Bliss", 
    "Efrén, Marionnettiste", 
    "Hydre de Lerne", 
    "Le Minotaure", 
    "L'Homme dans le Labyrinthe"
]

def ProcessString(String):
    return String.replace("é", "e").replace("è", "e").replace("ê", "e").replace("â", "a").replace("à", "a").replace("î", "i").replace("ō", "o").replace("ô", "o").lower().replace(",", "").replace("-", "").replace(" ", "").replace("'", "")

with open("./output.txt", "a", encoding = "utf-8") as f:
    for i in range(0, len(Cartes), 10):
        f.write("python ./scraping_uniques.py -faction bravos -name \"" + "¤".join(card for card in Cartes[i:i+10]) +"\" -radical \"script" + str(i) + "\"\n")
